name: BungeeTowny
api-version: 1.15
version: ${project.version}
main: com.paratopiamc.bungee_towny.BungeeTowny
authors: [ Oezingle ]
description: Towny across bungeecord instances!
softdepend: [PlaceholderAPI, Towny]

commands:
  chat:
    permission: bungeetowny.chat
    usage: Syntax error. Use /<command> <channel>
    description: the command to change channels. All other channel commands are ailases
  mute:
    permission: bungeetowny.mute
    usage: Syntax error. Use /<command> <player>
    description: a command to mute players across BungeeTowny's chat
  unmute:
    permission: bungeetowny.mute
    usage: Syntax error. Use /<command> <player>
    description: a command to unmute players across BungeeTowny's chat
  town:
    permission: bungeetowny.town
    usage: Syntax error. Use /<command>
    description: a stand-in for towny's /t and /town command
    aliases: [t]
  bungeetowny:
    permission: bungeetowny.admin
    usage: Syntax error. Use /<command>
    description: the administrative command

permissions:
  bungeetowny.chat:
    default: true
    description: allows use of /chat
  bungeetowny.mute:
    description: allows staff to /mute and /unmute
  bungeetowny.admin:
    description: admin parent node
    children:
      - bungeetowny.admin.reload
  bungeetowny.admin.reload:
    description: allows the /bungeetowny reload command
  bungeetowny.town:
    default: true
    description: allows using /town [arg] if towny isn't present on the server
    children:
      - bungeetowny.town.spawn
  bungeetowny.town.spawn:
    default: true
    description: allows using /town spawn from this server.