name: BungeeTowny
api-version: 1.15
version: ${project.version}
main: com.paratopiamc.bungee_towny.BungeeTowny
authors: [ Oezingle ]
description: Towny across bungeecord instances!
softdepend: [PlaceholderAPI, Towny]

commands:
  chat:
    permission: bungeetowny.chat
    usage: Syntax error. Use /chat <channel>
    description: the command to change channels. All other channel commands are ailases
  mute:
    permission: bungeetowny.chat.mute
    usage: Syntax error. Use /mute <player>
    description: a command to mute players across BungeeTowny's chat
  unmute:
    permission: bungeetowny.chat.mute
    usage: Syntax error. Use /unmute <player>
    description: a command to unmute players across BungeeTowny's chat
  town:
    permission: bungeetowny.town
    usage: Syntax error. Use /town
    description: a stand-in for towny's /t and /town command
    aliases: [t]
  bungeetowny:
    usage: Syntax error. Use /bungeetowny
    description: the administrative command
  message:
    usage: Syntax error. Use /message
    description: similar to vanilla msg, but players can toggle and send messages across the network
    permission: bungeetowny.chat.msg
  ignore:
    usage: Syntax error. Use /ignore <player>
    description: allows players to ignore each other's chat messages
    permission: bungeetowny.chat.ignore
    aliases: [unignore]

permissions:
  bungeetowny.chat:
    default: true
    description: allows use of /chat
    children:
      - bungeetowny.chat.msg
      - bungeetowny.chat.ignore
  bungeetowny.chat.msg:
    description: allows use of /msg <name> across the bungeetowny network
  bungeetowny.chat.ignore:
    description: allows use of /ignore <name> across the bungeetowny network
  bungeetowny.chat.mute:
    description: allows staff to /mute and /unmute
  bungeetowny.admin:
    description: admin parent node
    children:
      - bungeetowny.admin.reload
      - bungeetowny.admin.status
  bungeetowny.admin.reload:
    description: allows the [/bungeetowny reload] command
  bungeetowny.admin.status:
    description: allows the [/bungeetowny status] command
  bungeetowny.town:
    default: true
    description: allows using /town [arg] if towny isn't present on the server
    children:
      - bungeetowny.town.spawn
  bungeetowny.town.spawn:
    default: true
    description: allows using /town spawn from this server.